{
    "tests": [
        {
            "score": 0,
            "max_score": 25,
            "name": "test_uniq.py::test_stdin1[load-tests]",
            "output": "\ngroup_name = 'load-tests'\n\n    def new_func(group_name):\n        group_stat = group_stats[group_name]\n        if not group_stat['passed']:\n>           assert group_stat['observed'] == group_stat['expected']\nE           assert 'Traceback (most recent call last):\\n  File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py\", line 59, in dialog_exec\\n    executable = executable()\\n                 ^^^^^^^^^^^^\\n  File \"/Users/samwarr/filesync/cs235-assignments/Unit02-STL-data-structures/homework2a-uniq/test_uniq.py\", line 7, in uniq_bin\\n    return compile_cpp(\\'*.cpp\\', output_exec=\\'uniq\\')\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/cpp_utils.py\", line 12, in compile_cpp\\n    raise Exception(f\\'\"{command}\" failed:\\\\n{proc.stdout}\\')\\nException: \"g++ -Wall -std=c++17 -o uniq *.cpp\" failed:\\nduplicate symbol \\'_main\\' in:\\n    /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/lecture-10a580.o\\n    /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/uniq-7617ca.o\\nld: 1 duplicate symbols\\nclang: error: linker command failed with exit code 1 (use -v to see invocation)\\n\\n' == ''\nE             + Traceback (most recent call last):\nE             +   File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py\", line 59, in dialog_exec\nE             +     executable = executable()\nE             +                  ^^^^^^^^^^^^\nE             +   File \"/Users/samwarr/filesync/cs235-assignments/Unit02-STL-data-structures/homework2a-uniq/test_uniq.py\", line 7, in uniq_bin\nE             +     return compile_cpp('*.cpp', output_exec='uniq')\nE             +            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE             +   File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/cpp_utils.py\", line 12, in compile_cpp\nE             +     raise Exception(f'\"{command}\" failed:\\n{proc.stdout}')\nE             + Exception: \"g++ -Wall -std=c++17 -o uniq *.cpp\" failed:\nE             + duplicate symbol '_main' in:\nE             +     /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/lecture-10a580.o\nE             +     /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/uniq-7617ca.o\nE             + ld: 1 duplicate symbols\nE             + clang: error: linker command failed with exit code 1 (use -v to see invocation)\nE             +\n\n/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py:31: AssertionError",
            "visibility": "visible"
        },
        {
            "score": 0,
            "max_score": 25,
            "name": "test_uniq.py::test_stdin2[load-tests]",
            "output": "\ngroup_name = 'load-tests'\n\n    def new_func(group_name):\n        group_stat = group_stats[group_name]\n        if not group_stat['passed']:\n>           assert group_stat['observed'] == group_stat['expected']\nE           assert 'Traceback (most recent call last):\\n  File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py\", line 59, in dialog_exec\\n    executable = executable()\\n                 ^^^^^^^^^^^^\\n  File \"/Users/samwarr/filesync/cs235-assignments/Unit02-STL-data-structures/homework2a-uniq/test_uniq.py\", line 7, in uniq_bin\\n    return compile_cpp(\\'*.cpp\\', output_exec=\\'uniq\\')\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/cpp_utils.py\", line 12, in compile_cpp\\n    raise Exception(f\\'\"{command}\" failed:\\\\n{proc.stdout}\\')\\nException: \"g++ -Wall -std=c++17 -o uniq *.cpp\" failed:\\nduplicate symbol \\'_main\\' in:\\n    /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/lecture-b2d5ec.o\\n    /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/uniq-da7509.o\\nld: 1 duplicate symbols\\nclang: error: linker command failed with exit code 1 (use -v to see invocation)\\n\\n' == ''\nE             + Traceback (most recent call last):\nE             +   File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py\", line 59, in dialog_exec\nE             +     executable = executable()\nE             +                  ^^^^^^^^^^^^\nE             +   File \"/Users/samwarr/filesync/cs235-assignments/Unit02-STL-data-structures/homework2a-uniq/test_uniq.py\", line 7, in uniq_bin\nE             +     return compile_cpp('*.cpp', output_exec='uniq')\nE             +            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE             +   File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/cpp_utils.py\", line 12, in compile_cpp\nE             +     raise Exception(f'\"{command}\" failed:\\n{proc.stdout}')\nE             + Exception: \"g++ -Wall -std=c++17 -o uniq *.cpp\" failed:\nE             + duplicate symbol '_main' in:\nE             +     /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/lecture-b2d5ec.o\nE             +     /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/uniq-da7509.o\nE             + ld: 1 duplicate symbols\nE             + clang: error: linker command failed with exit code 1 (use -v to see invocation)\nE             +\n\n/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py:31: AssertionError",
            "visibility": "visible"
        },
        {
            "score": 0,
            "max_score": 25,
            "name": "test_uniq.py::test_file1[load-tests]",
            "output": "\ngroup_name = 'load-tests'\n\n    def new_func(group_name):\n        group_stat = group_stats[group_name]\n        if not group_stat['passed']:\n>           assert group_stat['observed'] == group_stat['expected']\nE           assert 'Traceback (most recent call last):\\n  File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py\", line 59, in dialog_exec\\n    executable = executable()\\n                 ^^^^^^^^^^^^\\n  File \"/Users/samwarr/filesync/cs235-assignments/Unit02-STL-data-structures/homework2a-uniq/test_uniq.py\", line 7, in uniq_bin\\n    return compile_cpp(\\'*.cpp\\', output_exec=\\'uniq\\')\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/cpp_utils.py\", line 12, in compile_cpp\\n    raise Exception(f\\'\"{command}\" failed:\\\\n{proc.stdout}\\')\\nException: \"g++ -Wall -std=c++17 -o uniq *.cpp\" failed:\\nduplicate symbol \\'_main\\' in:\\n    /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/lecture-3328a3.o\\n    /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/uniq-80f231.o\\nld: 1 duplicate symbols\\nclang: error: linker command failed with exit code 1 (use -v to see invocation)\\n\\n' == ''\nE             + Traceback (most recent call last):\nE             +   File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py\", line 59, in dialog_exec\nE             +     executable = executable()\nE             +                  ^^^^^^^^^^^^\nE             +   File \"/Users/samwarr/filesync/cs235-assignments/Unit02-STL-data-structures/homework2a-uniq/test_uniq.py\", line 7, in uniq_bin\nE             +     return compile_cpp('*.cpp', output_exec='uniq')\nE             +            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE             +   File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/cpp_utils.py\", line 12, in compile_cpp\nE             +     raise Exception(f'\"{command}\" failed:\\n{proc.stdout}')\nE             + Exception: \"g++ -Wall -std=c++17 -o uniq *.cpp\" failed:\nE             + duplicate symbol '_main' in:\nE             +     /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/lecture-3328a3.o\nE             +     /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/uniq-80f231.o\nE             + ld: 1 duplicate symbols\nE             + clang: error: linker command failed with exit code 1 (use -v to see invocation)\nE             +\n\n/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py:31: AssertionError",
            "visibility": "visible"
        },
        {
            "score": 0,
            "max_score": 25,
            "name": "test_uniq.py::test_file2[load-tests]",
            "output": "\ngroup_name = 'load-tests'\n\n    def new_func(group_name):\n        group_stat = group_stats[group_name]\n        if not group_stat['passed']:\n>           assert group_stat['observed'] == group_stat['expected']\nE           assert 'Traceback (most recent call last):\\n  File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py\", line 59, in dialog_exec\\n    executable = executable()\\n                 ^^^^^^^^^^^^\\n  File \"/Users/samwarr/filesync/cs235-assignments/Unit02-STL-data-structures/homework2a-uniq/test_uniq.py\", line 7, in uniq_bin\\n    return compile_cpp(\\'*.cpp\\', output_exec=\\'uniq\\')\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/cpp_utils.py\", line 12, in compile_cpp\\n    raise Exception(f\\'\"{command}\" failed:\\\\n{proc.stdout}\\')\\nException: \"g++ -Wall -std=c++17 -o uniq *.cpp\" failed:\\nduplicate symbol \\'_main\\' in:\\n    /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/lecture-6c7223.o\\n    /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/uniq-b3d8ea.o\\nld: 1 duplicate symbols\\nclang: error: linker command failed with exit code 1 (use -v to see invocation)\\n\\n' == ''\nE             + Traceback (most recent call last):\nE             +   File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py\", line 59, in dialog_exec\nE             +     executable = executable()\nE             +                  ^^^^^^^^^^^^\nE             +   File \"/Users/samwarr/filesync/cs235-assignments/Unit02-STL-data-structures/homework2a-uniq/test_uniq.py\", line 7, in uniq_bin\nE             +     return compile_cpp('*.cpp', output_exec='uniq')\nE             +            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE             +   File \"/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/cpp_utils.py\", line 12, in compile_cpp\nE             +     raise Exception(f'\"{command}\" failed:\\n{proc.stdout}')\nE             + Exception: \"g++ -Wall -std=c++17 -o uniq *.cpp\" failed:\nE             + duplicate symbol '_main' in:\nE             +     /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/lecture-6c7223.o\nE             +     /private/var/folders/89/lhsbyjrs2jqbtplq27dphm700000gn/T/uniq-b3d8ea.o\nE             + ld: 1 duplicate symbols\nE             + clang: error: linker command failed with exit code 1 (use -v to see invocation)\nE             +\n\n/opt/homebrew/lib/python3.11/site-packages/byu_pytest_utils/dialog.py:31: AssertionError",
            "visibility": "visible"
        }
    ]
}